# general
line-length = 120
target-version = "py310"

[lint]
# rules according to: https://docs.astral.sh/ruff/rules/
select = [
    "B",  # pyflakes-bugbear
    "C4", # flake8-comprehensions
    "E",  # pycodestyle Error
    "F",  # Pyflakes
    "I",  # isort
    "N",  # pep8-naming
    "W",  # pycodestyle Warning
]

ignore = [
    "B028", # stacklevel in warnings.warn — default (1) is fine for this project
    "E501", # line too long
]

[format]
indent-style = "space"
