MIN_BOX_AREA = 50
IGNORE_SIZE_LABELS = []
SEARCHAD_CATEGORIES = [
    "Animal",
    "Human",
    "Marking",
    "Object",
    "Rideable",
    "Scene",
    "Sign",
    "Trailer",
    "Vehicle",
]
# All subdataset directory names (union across all splits).
SEARCHAD_DATASETS = [
    "acdc",
    "bdd100k_images_100k",
    "cityscapes",
    "ECP",
    "IDD_Segmentation",
    "kitti",
    "lostandfound",
    "mapillary_sign",
    "mapillary_vistas",
    "nuscenes",
    "wd_both02",
    "wd_publicv2p0",
]
# Per-split dataset lists — not all subdatasets appear in every split.
SEARCHAD_TEST_DATASETS = [
    "acdc",
    "bdd100k_images_100k",
    "cityscapes",
    "ECP",
    "IDD_Segmentation",
    "kitti",
    "lostandfound",
    "mapillary_sign",
    "mapillary_vistas",
    "nuscenes",
    "wd_both02",
]
SEARCHAD_TRAIN_DATASETS = [
    "acdc",
    "bdd100k_images_100k",
    "cityscapes",
    "ECP",
    "IDD_Segmentation",
    "kitti",
    "lostandfound",
    "mapillary_sign",
    "mapillary_vistas",
    "nuscenes",
    "wd_publicv2p0",
]
SEARCHAD_VAL_DATASETS = [
    "acdc",
    "bdd100k_images_100k",
    "cityscapes",
    "ECP",
    "IDD_Segmentation",
    "mapillary_sign",
    "mapillary_vistas",
    "nuscenes",
    "wd_publicv2p0",
]
SEARCHAD_LABELS = [
    "Animal-Real-Cat",
    "Animal-Real-Cow",
    "Animal-Real-Deer",
    "Animal-Real-Dog",
    "Animal-Real-Donkey",
    "Animal-Real-Wildlife",
    "Animal-Real-Horse",
    "Animal-Real-Sheep",
    "Animal-Statue-Cow",
    "Animal-Statue-Deer",
    "Animal-Statue-Elephant",
    "Animal-Statue-Horse",
    "Animal-Statue-Lion",
    "Human-Construction-Worker",
    "Human-Firefighter",
    "Human-Medical",
    "Human-On-Loading-Area",
    "Human-Police",
    "Human-Refuse-Collector",
    "Human-With-Sticks-or-Crutches",
    "Marking-Bicycle-Symbol",
    "Marking-Bus-Text",
    "Marking-Stop-Text",
    "Marking-Temporarily-Invalidated",
    "Marking-Yellow-Lane-Arrow",
    "Object-Ball",
    "Object-Beacon",
    "Object-Euro-Pallet",
    "Object-Hand-Dolly",
    "Object-Hydrant",
    "Object-Office-Chair",
    "Object-Pallet-Truck",
    "Object-Platform-Truck",
    "Object-Rollator",
    "Object-Shopping-Cart",
    "Object-Shopping-Trolley",
    "Object-Suitcase-Trolley",
    "Object-Traffic-Cone",
    "Object-Trash-Bin",
    "Object-Wheelbarrow",
    "Rideable-Cityscooter",
    "Rideable-Police-Motorcycle",
    "Rideable-Quad",
    "Rideable-Segway",
    "Rideable-Skateboard",
    "Rideable-Skates",
    "Rideable-Ski",
    "Rideable-Stroller",
    "Rideable-Three-Wheeler",
    "Rideable-Toy-Car",
    "Rideable-Wheelchair",
    "Scene-Active-Amber-Lights",
    "Scene-Active-Emergency-Lights",
    "Scene-Fog",
    "Scene-Open-Door",
    "Scene-Open-Hood",
    "Scene-Open-Trunk",
    "Scene-Snow",
    "Scene-Tunnel",
    "Sign-Animal-Sign",
    "Sign-Road-Bumper-Sign",
    "Sign-Temporarily-Invalidated-Sign",
    "Sign-Train-Sign",
    "Sign-Warning-Triangle",
    "Trailer-Agricultural-Trailer",
    "Trailer-Bicycle-Trailer",
    "Trailer-Boat-Trailer",
    "Trailer-Car-Trailer",
    "Trailer-Caravan-Trailer",
    "Trailer-Carriage",
    "Trailer-Warning-Trailer",
    "Vehicle-Construction-Concrete-Mixer",
    "Vehicle-Construction-Excavator",
    "Vehicle-Construction-Forklift",
    "Vehicle-Construction-Harvester",
    "Vehicle-Construction-Loader",
    "Vehicle-Construction-Steamroller",
    "Vehicle-Construction-Tractor",
    "Vehicle-Construction-Truck-Crane",
    "Vehicle-Duty-Fire",
    "Vehicle-Duty-Garbage",
    "Vehicle-Duty-Medical",
    "Vehicle-Duty-Military",
    "Vehicle-Duty-Police",
    "Vehicle-Duty-Winter",
    "Vehicle-Special-Bicycle-On-Back",
    "Vehicle-Special-Bicycle-On-Roof",
    "Vehicle-Special-Car-Truck",
    "Vehicle-Special-Recreational",
    "Vehicle-Special-Train",
]
LABEL_COLORS = {
    "Animal-Real-Cat": (255, 192, 203),
    "Animal-Real-Cow": (255, 160, 122),
    "Animal-Real-Deer": (139, 69, 19),
    "Animal-Real-Dog": (250, 128, 114),
    "Animal-Real-Donkey": (100, 149, 237),
    "Animal-Real-Horse": (244, 164, 96),
    "Animal-Real-Sheep": (34, 139, 34),
    "Animal-Real-Wildlife": (128, 128, 0),
    "Animal-Statue-Cow": (173, 216, 230),
    "Animal-Statue-Deer": (255, 228, 181),
    "Animal-Statue-Elephant": (192, 192, 192),
    "Animal-Statue-Horse": (205, 133, 63),
    "Animal-Statue-Lion": (255, 165, 0),
    "Human-Construction-Worker": (255, 215, 0),
    "Human-Firefighter": (148, 0, 211),
    "Human-Medical": (75, 0, 130),
    "Human-On-Loading-Area": (127, 255, 0),
    "Human-Police": (218, 112, 214),
    "Human-Refuse-Collector": (119, 136, 153),
    "Human-With-Sticks-or-Crutches": (124, 252, 0),
    "Marking-Bicycle-Symbol": (0, 128, 0),
    "Marking-Bus-Text": (128, 0, 128),
    "Marking-Stop-Text": (255, 0, 0),
    "Marking-Temporarily-Invalidated": (245, 245, 220),
    "Marking-Yellow-Lane-Arrow": (255, 255, 0),
    "Object-Ball": (0, 255, 255),
    "Object-Beacon": (128, 0, 0),
    "Object-Euro-Pallet": (210, 105, 30),
    "Object-Hand-Dolly": (169, 169, 169),
    "Object-Hydrant": (178, 34, 34),
    "Object-Office-Chair": (85, 107, 47),
    "Object-Pallet-Truck": (112, 128, 144),
    "Object-Platform-Truck": (144, 238, 144),
    "Object-Rollator": (50, 205, 50),
    "Object-Shopping-Cart": (192, 192, 192),
    "Object-Shopping-Trolley": (160, 82, 45),
    "Object-Suitcase-Trolley": (105, 105, 105),
    "Object-Traffic-Cone": (238, 232, 170),
    "Object-Trash-Bin": (112, 128, 144),
    "Object-Wheelbarrow": (184, 134, 11),
    "Rideable-Cityscooter": (0, 128, 0),
    "Rideable-Police-Motorcycle": (0, 250, 154),
    "Rideable-Quad": (60, 179, 113),
    "Rideable-Segway": (255, 20, 147),
    "Rideable-Skateboard": (255, 99, 71),
    "Rideable-Skates": (255, 140, 0),
    "Rideable-Ski": (135, 206, 250),
    "Rideable-Stroller": (240, 255, 240),
    "Rideable-Three-Wheeler": (255, 235, 205),
    "Rideable-Toy-Car": (255, 255, 224),
    "Rideable-Wheelchair": (72, 61, 139),
    "Scene-Active-Amber-Lights": (255, 191, 0),
    "Scene-Active-Emergency-Lights": (255, 0, 0),
    "Scene-Fog": (220, 220, 220),
    "Scene-Open-Door": (139, 69, 19),
    "Scene-Open-Hood": (128, 0, 0),
    "Scene-Open-Trunk": (0, 100, 0),
    "Scene-Snow": (200, 200, 200),
    "Scene-Tunnel": (70, 130, 180),
    "Sign-Animal-Sign": (255, 0, 255),
    "Sign-Road-Bumper-Sign": (107, 142, 35),
    "Sign-Temporarily-Invalidated-Sign": (255, 228, 196),
    "Sign-Train-Sign": (105, 105, 105),
    "Sign-Warning-Triangle": (106, 90, 205),
    "Trailer-Agricultural-Trailer": (152, 251, 152),
    "Trailer-Bicycle-Trailer": (0, 0, 128),
    "Trailer-Boat-Trailer": (128, 128, 0),
    "Trailer-Car-Trailer": (189, 183, 107),
    "Trailer-Caravan-Trailer": (240, 230, 140),
    "Trailer-Carriage": (245, 222, 179),
    "Trailer-Warning-Trailer": (123, 104, 238),
    "Vehicle-Construction-Concrete-Mixer": (0, 191, 255),
    "Vehicle-Construction-Excavator": (135, 206, 235),
    "Vehicle-Construction-Forklift": (240, 128, 128),
    "Vehicle-Construction-Harvester": (0, 0, 255),
    "Vehicle-Construction-Loader": (219, 112, 147),
    "Vehicle-Construction-Steamroller": (186, 85, 211),
    "Vehicle-Construction-Tractor": (0, 255, 0),
    "Vehicle-Construction-Truck-Crane": (147, 112, 219),
    "Vehicle-Duty-Fire": (176, 196, 222),
    "Vehicle-Duty-Garbage": (255, 182, 193),
    "Vehicle-Duty-Medical": (216, 191, 216),
    "Vehicle-Duty-Military": (238, 130, 238),
    "Vehicle-Duty-Police": (221, 160, 221),
    "Vehicle-Duty-Winter": (176, 224, 230),
    "Vehicle-Special-Bicycle-On-Back": (64, 64, 64),
    "Vehicle-Special-Bicycle-On-Roof": (192, 192, 192),
    "Vehicle-Special-Car-Truck": (0, 128, 128),
    "Vehicle-Special-Recreational": (46, 139, 87),
    "Vehicle-Special-Train": (139, 137, 137),
}

# ── Visualization parameters ────────────────────────────────────────────────
# Bounding-box / label rendering
BORDER_WIDTH = 5  # Width of the image border (retrieval visualization)
BBOX_LINE_WIDTH = 5  # Width of drawn bounding box rectangles
FONT_SCALE = 2  # cv2 font scale for annotation labels
FONT_THICKNESS = 3  # cv2 font thickness for annotation labels
TEXT_PADDING = 5  # Pixel padding around label text
DEFAULT_COLOR_RGB = (255, 255, 255)

# Retrieval collage layout
COLLAGE_RESIZE_DIM = (1920, 1080)  # (width, height) each image cell is resized to
COLLAGE_TITLE_FONTSIZE = 64  # Matplotlib font size for the suptitle
COLLAGE_SUBTITLE_FONTSIZE = 64  # Matplotlib font size for per-image subcaptions
COLLAGE_H_PAD = 0.0  # Vertical gap (inches) between collage rows
COLLAGE_W_PAD = 1.0  # Horizontal gap (inches) between collage columns

# ── Dataset download ────────────────────────────────────────────────────────
SEARCHAD_HF_URL = "https://huggingface.co/datasets/iis-esslingen/SearchAD/resolve/main/searchad.zip"

DATASET_DOWNLOAD_INSTRUCTIONS = [
    {
        "name": "Lost and Found",
        "folder": "lostandfound",
        "url": "https://huggingface.co/datasets/iis-esslingen/LostAndFoundDataset",
        "instructions": "Download leftImg8bit/",
        "requires_account": False,
    },
    {
        "name": "WildDash2",
        "folder": "wd_both02 and wd_publicv2p0",
        "url": "https://www.wilddash.cc/accounts/login?next=/download",
        "instructions": "Download wd_public_v2p0.zip and wd_both_02.zip",
        "requires_account": True,
    },
    {
        "name": "ACDC",
        "folder": "acdc",
        "url": "https://acdc.vision.ee.ethz.ch/download",
        "instructions": "Download rgb_anon_trainvaltest.zip",
        "requires_account": True,
    },
    {
        "name": "IDD Segmentation",
        "folder": "IDD_Segmentation",
        "url": "https://idd.insaan.iiit.ac.in/accounts/login/?next=/dataset/download/",
        "instructions": "Download IDD Segmentation (IDD 20k Part I) (18.5 GB)",
        "requires_account": True,
    },
    {
        "name": "KITTI",
        "folder": "kitti",
        "url": "https://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=2d",
        "instructions": "Download left color images of object data set (12 GB)",
        "requires_account": False,
    },
    {
        "name": "Cityscapes",
        "folder": "cityscapes",
        "url": "https://www.cityscapes-dataset.com/downloads/",
        "instructions": "Download leftImg8bit_trainvaltest.zip and leftImg8bit_trainextra.zip",
        "requires_account": True,
    },
    {
        "name": "Mapillary Vistas",
        "folder": "mapillary_vistas",
        "url": "https://www.mapillary.com/dataset/vistas",
        "instructions": "Download mapillary-vistas-dataset_public_v2.0.zip",
        "requires_account": True,
    },
    {
        "name": "ECP",
        "folder": "ECP",
        "url": "https://eurocity-dataset.tudelft.nl/eval/downloads/detection",
        "instructions": "Download ECP day and night, train, val, test (6 zip files)",
        "requires_account": True,
    },
    {
        "name": "nuScenes",
        "folder": "nuscenes",
        "url": "https://www.nuscenes.org/nuscenes#download",
        "instructions": "Download Trainval and Test",
        "requires_account": True,
    },
    {
        "name": "BDD100K",
        "folder": "bdd100k_images_100k",
        "url": "http://bdd-data.berkeley.edu/download.html",
        "instructions": "Download 100K Images",
        "requires_account": True,
    },
    {
        "name": "Mapillary Sign",
        "folder": "mapillary_sign",
        "url": "https://www.mapillary.com/dataset/trafficsign",
        "instructions": "Click Download dataset",
        "requires_account": True,
    },
]
